build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: false

complexity:
  active: true
  ComplexMethod:
    active: true
    threshold: 18
  LargeClass:
    active: true
    threshold: 550
  LongMethod:
    active: true
    threshold: 110
  LongParameterList:
    active: true
    functionThreshold: 12
    constructorThreshold: 12
    ignoreDefaultParameters: true
    ignoreDataClasses: true
  TooManyFunctions:
    active: true
    thresholdInFiles: 40
    thresholdInClasses: 24
    thresholdInInterfaces: 18

comments:
  active: true
  UndocumentedPublicClass:
    active: true
    searchInNestedClass: true
  UndocumentedPublicFunction:
    active: true

naming:
  active: true
  ClassNaming:
    active: true
  FunctionNaming:
    active: true
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  VariableNaming:
    active: true

style:
  active: true
  MagicNumber:
    active: true
    ignorePropertyDeclaration: true
    ignoreLocalVariableDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreNamedArgument: true
  WildcardImport:
    active: true
  UnusedPrivateMember:
    active: true
